name = "Flexpart"
uuid = "fb362612-c2d8-4302-a9fd-a07f2890630f"
authors = ["Tristan Carion <tristancarion@gmail.com> and contributors"]
version = "0.2.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
FLEXPART_jll = "f469b0c9-c763-5b61-b20e-7fa8370129c5"
GRIB = "b16dfd50-4035-11e9-28d4-9dfe17e6779b"
NCDatasets = "85f8d34a-cbdd-5861-8df4-14fed0d494ab"
NetCDFF_jll = "78e728a9-57fe-5d11-897c-5014b89e5f84"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"

[compat]
DataStructures = "0.18"
DocStringExtensions = "0.9"
GRIB = "0.3"
julia = "1"
